name: Run tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16, 18, 20]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Run Tests
        run: npm test
